/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WebGlImport } from './routes/web-gl'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WebGlRoute = WebGlImport.update({
  id: '/web-gl',
  path: '/web-gl',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/web-gl': {
      id: '/web-gl'
      path: '/web-gl'
      fullPath: '/web-gl'
      preLoaderRoute: typeof WebGlImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/web-gl': typeof WebGlRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/web-gl': typeof WebGlRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/web-gl': typeof WebGlRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/web-gl'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/web-gl'
  id: '__root__' | '/' | '/web-gl'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WebGlRoute: typeof WebGlRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WebGlRoute: WebGlRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/web-gl"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/web-gl": {
      "filePath": "web-gl.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
